<!-- BEGIN: MAIN -->
<form method="GET" action="{PHP|cot_url('plug', 'e=searchforms')}">
  <input type="hidden" name="e" value="searchforms">
  <input type="hidden" name="code" value="{CODE}">
  <table class="cells">
    <tr>
      <td colspan="3" align="center">Страницы</td>
    </tr>
    <tr>
      <td>{PHP.L.Category}:</td>
      <td>{PAGE_SEARCH_CAT}</td>
      <td>{PAGE_SORT_CAT}</td>
    </tr>
    <tr>
      <td>ID:</td>
      <td>{PAGE_SEARCH_ID}</td>
      <td>{PAGE_SORT_ID}</td>
    </tr>
    <tr>
      <td>{PHP.L.Title}:</td>
      <td>{PAGE_SEARCH_TITLE}</td>
      <td>{PAGE_SORT_TITLE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Description}:</td>
      <td>{PAGE_SEARCH_DESC}</td>
      <td>{PAGE_SORT_DESC}</td>
    </tr>
    <tr>
      <td>{PHP.L.Text}:</td>
      <td>{PAGE_SEARCH_TEXT}</td>
      <td>{PAGE_SORT_TEXT}</td>
    </tr>
    <tr>
      <td>{PHP.L.page_metakeywords}:</td>
      <td>{PAGE_SEARCH_KEYWORDS}</td>
      <td>{PAGE_SORT_KEYWORDS}</td>
    </tr>
    <tr>
      <td>{PHP.L.page_metatitle}:</td>
      <td>{PAGE_SEARCH_METATITLE}</td>
      <td>{PAGE_SORT_METATITLE}</td>
    </tr>
    <tr>
      <td>{PHP.L.page_metadesc}:</td>
      <td>{PAGE_SEARCH_METADESC}</td>
      <td>{PAGE_SORT_METADESC}</td>
    </tr>
    <tr>
      <td>{PHP.L.Author}:</td>
      <td>{PAGE_SEARCH_AUTHOR}</td>
      <td>{PAGE_SORT_AUTHOR}</td>
    </tr>
    <tr>
      <td>{PHP.L.Date}:</td>
      <td>{PAGE_SEARCH_DATE}</td>
      <td>{PAGE_SORT_DATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Hits}:</td>
      <td>{PAGE_SEARCH_HITS}</td>
      <td>{PAGE_SORT_HITS}</td>
    </tr>
    <tr>
      <td>{PHP.L.Date}:</td>
      <td>{PAGE_SEARCH_DATE}</td>
      <td>{PAGE_SORT_DATE}</td>
    </tr>
    <tr>
      <td colspan="3" align="center">Магазин</td>
    </tr>
    <tr>
      <td>ID:</td>
      <td>{MARKET_SEARCH_ID}</td>
      <td>{MARKET_SORT_ID}</td>
    </tr>
    <tr>
      <td>{PHP.L.Category}:</td>
      <td>{MARKET_SEARCH_CAT}</td>
      <td>{MARKET_SORT_CAT}</td>
    </tr>
    <tr>
      <td>{PHP.L.Title}:</td>
      <td>{MARKET_SEARCH_TITLE}</td>
      <td>{MARKET_SORT_TITLE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Text}:</td>
      <td>{MARKET_SEARCH_TEXT}</td>
      <td>{MARKET_SORT_TEXT}</td>
    </tr>
    <tr>
      <td>{PHP.L.projects_price}:</td>
      <td>{MARKET_SEARCH_COST}</td>
      <td>{MARKET_SORT_COST}</td>
    </tr>
    <tr>
      <td>{PHP.L.Date}:</td>
      <td>{MARKET_SEARCH_DATE}</td>
      <td>{MARKET_SORT_DATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Update}:</td>
      <td>{MARKET_SEARCH_UPDATE}</td>
      <td>{MARKET_SORT_UPDATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Hits}:</td>
      <td>{MARKET_SEARCH_HITS}</td>
      <td>{MARKET_SORT_HITS}</td>
    </tr>
    <tr>
      <td colspan="3" align="center">Проекты</td>
    </tr>
    <tr>
      <td>ID:</td>
      <td>{PROJECTS_SEARCH_ID}</td>
      <td>{PROJECTS_SORT_ID}</td>
    </tr>
    <tr>
      <td>{PHP.L.Category}:</td>
      <td>{PROJECTS_SEARCH_CAT}</td>
      <td>{PROJECTS_SORT_CAT}</td>
    </tr>
    <tr>
      <td>{PHP.L.Title}:</td>
      <td>{PROJECTS_SEARCH_TITLE}</td>
      <td>{PROJECTS_SORT_TITLE}</td>
    </tr>
    <tr>
      <td>Описание:</td>
      <td>{PROJECTS_SEARCH_TEXT}</td>
      <td>{PROJECTS_SORT_TEXT}</td>
    </tr>
    <tr>
      <td>Цена:</td>
      <td>{PROJECTS_SEARCH_COST}</td>
      <td>{PROJECTS_SORT_COST}</td>
    </tr>
    <tr>
      <td>{PHP.L.Date}:</td>
      <td>{PROJECTS_SEARCH_DATE}</td>
      <td>{PROJECTS_SORT_DATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Update}:</td>
      <td>{PROJECTS_SEARCH_UPDATE}</td>
      <td>{PROJECTS_SORT_UPDATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Hits}:</td>
      <td>{PROJECTS_SEARCH_HITS}</td>
      <td>{PROJECTS_SORT_HITS}</td>
    </tr>
    <tr>
      <td colspan="3" align="center">Demands</td>
    </tr>
    <tr>
      <td>ID:</td>
      <td>{DEMANDS_SEARCH_ID}</td>
      <td>{DEMANDS_SORT_ID}</td>
    </tr>
    <tr>
      <td>{PHP.L.Category}:</td>
      <td>{DEMANDS_SEARCH_CAT}</td>
      <td>{DEMANDS_SORT_CAT}</td>
    </tr>
    <tr>
      <td>{PHP.L.Title}:</td>
      <td>{DEMANDS_SEARCH_TITLE}</td>
      <td>{DEMANDS_SORT_TITLE}</td>
    </tr>
    <tr>
      <td>Описание:</td>
      <td>{DEMANDS_SEARCH_TEXT}</td>
      <td>{DEMANDS_SORT_TEXT}</td>
    </tr>
    <tr>
      <td>Цена:</td>
      <td>{DEMANDS_SEARCH_COST}</td>
      <td>{DEMANDS_SORT_COST}</td>
    </tr>
    <tr>
      <td>{PHP.L.Date}:</td>
      <td>{DEMANDS_SEARCH_DATE}</td>
      <td>{DEMANDS_SORT_DATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Update}:</td>
      <td>{DEMANDS_SEARCH_UPDATE}</td>
      <td>{DEMANDS_SORT_UPDATE}</td>
    </tr>
    <tr>
      <td>{PHP.L.Hits}:</td>
      <td>{DEMANDS_SEARCH_HITS}</td>
      <td>{DEMANDS_SORT_HITS}</td>
    </tr>
    <tr>
      <td><input type="submit" value="{PHP.L.Search}" class="btn"></td>
      <td></td>
      <td></td>
    </tr>
  </table>
</form>
<!-- END: MAIN -->